services:
  api:
    container_name: fedal-api-r2d2
    image: ${IMAGE_REPOSITORY:-ghcr.io/fedal-nl/fedal-r2d2}:${IMAGE_TAG:-latest}
    pull_policy: always
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:8000:8000"
