"""zaansrecht form created

Revision ID: ffb7e7b7571a
Revises: 6d678f5c1f35
Create Date: 2025-10-27 21:35:19.562881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb7e7b7571a'
down_revision: Union[str, Sequence[str], None] = '6d678f5c1f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zaansrecht_form',
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zaansrecht_form_id'), 'zaansrecht_form', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zaansrecht_form_id'), table_name='zaansrecht_form')
    op.drop_table('zaansrecht_form')
    # ### end Alembic commands ###
