"""add more form fields

Revision ID: 19ebc82230e5
Revises: ffb7e7b7571a
Create Date: 2025-10-28 20:24:00.443417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ebc82230e5'
down_revision: Union[str, Sequence[str], None] = 'ffb7e7b7571a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zaansrecht_form', sa.Column('meeting_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('zaansrecht_form', sa.Column('meeting_type', sa.String(), nullable=True))
    op.add_column('zaansrecht_form', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('zaansrecht_form', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zaansrecht_form', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('zaansrecht_form', 'full_name')
    op.drop_column('zaansrecht_form', 'meeting_type')
    op.drop_column('zaansrecht_form', 'meeting_datetime')
    # ### end Alembic commands ###
