"""<migration_message>

Revision ID: 2797ca993b35
Revises: e6034481a741
Create Date: 2026-02-26 15:27:50.846415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2797ca993b35'
down_revision: Union[str, Sequence[str], None] = 'e6034481a741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('OPENAI', 'GOOGLE', 'ANTHROPIC', 'MISTRAL', 'XAI', 'LLAMA', name='ai_agent_enum'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ai_agents_created_at'), 'ai_agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_agents_updated_at'), 'ai_agents', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ai_agent_id', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_agent_id'], ['ai_agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_category_name_user')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_chapter_name_user')
    )
    op.create_index(op.f('ix_chapters_created_at'), 'chapters', ['created_at'], unique=False)
    op.create_index(op.f('ix_chapters_name'), 'chapters', ['name'], unique=False)
    op.create_index(op.f('ix_chapters_updated_at'), 'chapters', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chapters_user_id'), 'chapters', ['user_id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'user_id', name='uq_language_code_user'),
    sa.UniqueConstraint('name', 'user_id', name='uq_language_name_user')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=False)
    op.create_index(op.f('ix_languages_created_at'), 'languages', ['created_at'], unique=False)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=False)
    op.create_index(op.f('ix_languages_updated_at'), 'languages', ['updated_at'], unique=False)
    op.create_index(op.f('ix_languages_user_id'), 'languages', ['user_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_created_at'), 'quiz_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('social_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('FACEBOOK', 'TWITTER', 'INSTAGRAM', 'LINKEDIN', 'TIKTOK', 'GOOGLE', 'MICROSOFT', 'APPLE', 'AMAZON', 'GITHUB', 'SPOTIFY', 'EMAIL', name='social_media_platform_enum'), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_platform_user')
    )
    op.create_index(op.f('ix_social_providers_created_at'), 'social_providers', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_providers_user_id'), 'social_providers', ['user_id'], unique=False)
    op.create_table('vocabulary_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_vocabularytype_name_user')
    )
    op.create_index(op.f('ix_vocabulary_types_created_at'), 'vocabulary_types', ['created_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_types_name'), 'vocabulary_types', ['name'], unique=False)
    op.create_index(op.f('ix_vocabulary_types_updated_at'), 'vocabulary_types', ['updated_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_types_user_id'), 'vocabulary_types', ['user_id'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_type_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_type_id'], ['vocabulary_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'language_id', 'user_id', name='uq_vocabulary_text_language_user')
    )
    op.create_index(op.f('ix_vocabulary_chapter_id'), 'vocabulary', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_created_at'), 'vocabulary', ['created_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_language_id'), 'vocabulary', ['language_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_text'), 'vocabulary', ['text'], unique=False)
    op.create_index(op.f('ix_vocabulary_updated_at'), 'vocabulary', ['updated_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_user_id'), 'vocabulary', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_vocabulary_type_id'), 'vocabulary', ['vocabulary_type_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('answered_correctly', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_answered_at'), 'quiz_attempts', ['answered_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_answered_correctly'), 'quiz_attempts', ['answered_correctly'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_session_id'), 'quiz_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_vocabulary_id'), 'quiz_attempts', ['vocabulary_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vocabulary_id', 'translation')
    )
    op.create_index(op.f('ix_translations_created_at'), 'translations', ['created_at'], unique=False)
    op.create_index(op.f('ix_translations_language_id'), 'translations', ['language_id'], unique=False)
    op.create_index(op.f('ix_translations_vocabulary_id'), 'translations', ['vocabulary_id'], unique=False)
    op.create_table('verb_conjugations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('conjugation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verb_conjugations_created_at'), 'verb_conjugations', ['created_at'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_vocabulary_id'), 'verb_conjugations', ['vocabulary_id'], unique=False)
    op.create_table('vocabulary_categories',
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vocabulary_id', 'category_id')
    )
    op.create_index(op.f('ix_vocabulary_categories_created_at'), 'vocabulary_categories', ['created_at'], unique=False)
    op.create_table('vocabulary_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('ai_agent_id', sa.Integer(), nullable=True),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_agent_id'], ['ai_agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_examples_ai_agent_id'), 'vocabulary_examples', ['ai_agent_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_examples_created_at'), 'vocabulary_examples', ['created_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_examples_vocabulary_id'), 'vocabulary_examples', ['vocabulary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_examples_vocabulary_id'), table_name='vocabulary_examples')
    op.drop_index(op.f('ix_vocabulary_examples_created_at'), table_name='vocabulary_examples')
    op.drop_index(op.f('ix_vocabulary_examples_ai_agent_id'), table_name='vocabulary_examples')
    op.drop_table('vocabulary_examples')
    op.drop_index(op.f('ix_vocabulary_categories_created_at'), table_name='vocabulary_categories')
    op.drop_table('vocabulary_categories')
    op.drop_index(op.f('ix_verb_conjugations_vocabulary_id'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_created_at'), table_name='verb_conjugations')
    op.drop_table('verb_conjugations')
    op.drop_index(op.f('ix_translations_vocabulary_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_language_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_created_at'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_quiz_attempts_vocabulary_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_session_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_answered_correctly'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_answered_at'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_vocabulary_vocabulary_type_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_user_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_updated_at'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_text'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_language_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_created_at'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_chapter_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_vocabulary_types_user_id'), table_name='vocabulary_types')
    op.drop_index(op.f('ix_vocabulary_types_updated_at'), table_name='vocabulary_types')
    op.drop_index(op.f('ix_vocabulary_types_name'), table_name='vocabulary_types')
    op.drop_index(op.f('ix_vocabulary_types_created_at'), table_name='vocabulary_types')
    op.drop_table('vocabulary_types')
    op.drop_index(op.f('ix_social_providers_user_id'), table_name='social_providers')
    op.drop_index(op.f('ix_social_providers_created_at'), table_name='social_providers')
    op.drop_table('social_providers')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_created_at'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_languages_user_id'), table_name='languages')
    op.drop_index(op.f('ix_languages_updated_at'), table_name='languages')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_created_at'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_chapters_user_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_updated_at'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_name'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_created_at'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_agents_updated_at'), table_name='ai_agents')
    op.drop_index(op.f('ix_ai_agents_created_at'), table_name='ai_agents')
    op.drop_table('ai_agents')
    # ### end Alembic commands ###
