"""adding message body

Revision ID: 4a08ce8d2d1a
Revises: df1ff6bb5719
Create Date: 2025-10-25 23:46:47.694825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a08ce8d2d1a'
down_revision: Union[str, Sequence[str], None] = 'df1ff6bb5719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_logs', 'body')
    # ### end Alembic commands ###
