"""added captcha key for the zaansrecht form

Revision ID: 61dde2682d05
Revises: 19ebc82230e5
Create Date: 2025-10-30 19:18:13.232520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61dde2682d05'
down_revision: Union[str, Sequence[str], None] = '19ebc82230e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zaansrecht_form', sa.Column('captcha_token', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zaansrecht_form', 'captcha_token')
    # ### end Alembic commands ###
