"""added updated_at to have the latest update and changed the default from Pending to Queued

Revision ID: 6d678f5c1f35
Revises: 4a08ce8d2d1a
Create Date: 2025-10-26 18:28:47.287640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d678f5c1f35'
down_revision: Union[str, Sequence[str], None] = '4a08ce8d2d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_logs', 'updated_at')
    # ### end Alembic commands ###
