"""form submitlogger added with moving the captcha to the logger

Revision ID: e6034481a741
Revises: 61dde2682d05
Create Date: 2025-11-06 21:23:45.354884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6034481a741'
down_revision: Union[str, Sequence[str], None] = '61dde2682d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_submission_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('x_forwarded_for', postgresql.ARRAY(postgresql.INET()), nullable=True),
    sa.Column('x_real_ip', postgresql.INET(), nullable=True),
    sa.Column('captcha_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['zaansrecht_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submission_log_id'), 'form_submission_log', ['id'], unique=False)
    op.create_index(op.f('ix_form_submission_log_x_real_ip'), 'form_submission_log', ['x_real_ip'], unique=False)
    op.drop_column('zaansrecht_form', 'captcha_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zaansrecht_form', sa.Column('captcha_token', sa.VARCHAR(length=4096), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_form_submission_log_x_real_ip'), table_name='form_submission_log')
    op.drop_index(op.f('ix_form_submission_log_id'), table_name='form_submission_log')
    op.drop_table('form_submission_log')
    # ### end Alembic commands ###
